name: publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.title, "RELEASE" }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish
        run: |
          echo "running"
